CREATE TABLE USERS(
ID INT NOT NULL IDENTITY PRIMARY KEY,
USERNAME VARCHAR(41) NOT NULL,
PASSWORD VARCHAR(41) NOT NULL,
EMAIL VARCHAR(41) NOT NULL,
CREATED_DATE DATETIME
);

CREATE TABLE PORTFOLIO(
PORTFOLIO VARCHAR(41) NOT NULL PRIMARY KEY,
BALANCE MONEY NOT NULL,

USERNAME VARCHAR(41),
CONSTRAINT C_FK_1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME)

);
